### ISSUE TITLE
Two context menus

### ISSUE THREAD

**Issue by RicardoRamirezR** [johndatserakis/vue-simple-context-menu#1]
Hi there, starting to try you component, and it works very well only if is one menu on the page since you have the ul id hardcoded. is there any way to have more than one menu? thank you!

**Comment by RicardoRamirezR** [comment]
Maybe:
```html
<ul :id="id" class="vue-simple-context-menu" v-click-outside="onClickOutside">
    <li v-for="option in options" @click="optionClicked(option)" class="vue-simple-context-menu__item">
        {{option.name}}
    </li>
</ul>
```
```js
data () {
    return {
        ...
        id: null
    }
}, 
mounted () {
    this.id = "vue-simple-context-menu-id-" + this._uid;
}
```
of course, changing all references to ```this.id```

**Comment by johndatserakis** [comment]
Hey there - good idea! I'll get this up and pushed by tonight.

**Comment by RicardoRamirezR** [comment]
Great! Just a thing. Why is required the ```id``` when you can generate one like in the mounted function above, the ```this._uid```gives a different number for each component.
