### ISSUE TITLE
How do you activate on right vs left click?

### ISSUE THREAD

**Issue by craiggeil** [johndatserakis/vue-simple-context-menu#11]
I looked everywhere in your code, how do you tell the menu to only appear on a right click vs left click?

**Comment by johndatserakis** [comment]
Hey - use `@contextmenu.prevent.stop` to use it for right clicks, like this:

```javascript
@contextmenu.prevent.stop="handleClick($event, item)"
```

Let me know how it goes.

**Comment by craiggeil** [comment]
That worked. Totally missed this "Note - make sure to use @click.prevent.stop (or @contextmenu.prevent.stop for right click) when setting up the click handler." Sorry! Nice library, thanks for all the hard work in putting it together!

**Comment by johndatserakis** [comment]
No sweat - glad it's working.
