### ISSUE TITLE
Add a CSS-class per menu item

### ISSUE THREAD

**Issue by geri777** [johndatserakis/vue-simple-context-menu#12]
ENHANCEMENT: 

It would be great to be able to add a CSS Class to each menu item. This would help me to style each item differently - with icons, colors, etc.

```
var options = [
     {name: "Menu Item 1", cssClass:"alert", ...}
]
```

**Comment by johndatserakis** [comment]
I think this is a great idea - I'm a little tied up right at the moment though. When I get a chance to do this I'll update here - also anyone can jump in if they'd like.

The implementation should target the `options` array - each object may include an optional `class` property (in addition to the existing required `name` property) that will be added dynamically to the item `li`.

Thanks for the suggestion!

**Comment by johndatserakis** [comment]
Hey @geri777 - thanks for the suggestion. This feature is now added and is live at v3.1.6.

Thank you!
