### ISSUE TITLE
[FR] close menu on Esc key

### ISSUE THREAD

**Issue by laur89** [johndatserakis/vue-simple-context-menu#16]

**Comment by johndatserakis** [comment]
Good suggestion - I'll get to this as soon as I am able. Thank you!

**Comment by robertdrakedennis** [comment]
Couldn't you do something like ``@keydown.esc.exact="someHideMethod"?`` I know some might not want this functionality but surely this would be a good addition

**Comment by johndatserakis** [comment]
Alright I got a bit of time so I went ahead and added this to the latest `v3.1.8` release in the https://github.com/johndatserakis/vue-simple-context-menu/pull/17 pull request. Thank you @laur89 laur89 for the suggestion and @robertdrakedennis for the help.
