### ISSUE TITLE
Menu item names needs to be trimmed

### ISSUE THREAD

**Issue by mewcrazy** [johndatserakis/vue-simple-context-menu#19]
Hello,

I just noticed in my source code, that the strings of the context menu items contain lots of spaces or tabs and that messes up my source code. (not that it matters)

See the following image:
![image](https://user-images.githubusercontent.com/6299479/71624108-2ebd1100-2be1-11ea-83ca-6ff998942768.png)

**Comment by mewcrazy** [comment]
I just discoverd in your code that you wrapped a hardcoded newline and 4 spaces around the option.name.

**Comment by johndatserakis** [comment]
Hello @mewcrazy, I looked for that hardcoded newline but I don't see it in my editor. Could you by any chance show me exactly where you're seeing it? Strange...
