### ISSUE TITLE
Feature: Divider Line Support

### ISSUE THREAD

**Issue by mikeerickson** [johndatserakis/vue-simple-context-menu#27]
Curious if there has been thought of adding divider line support?  I am thinking it could be added into menu definition

```js
...
menuOptions: {
{
  name: "New Contact",
  slug: "new-contact",
},
{
  name: "-",
  slug: "divider",
},
{
  name: "New Company",
  slug: "new-company",
},
}
...
```

**Comment by johndatserakis** [comment]
Sure, I think that'd be a great addition. I'm think we could add a `type` property, and display a divider when the value `divider` is passed.

I'll try to get to this in the next week or so. Thank you.

**Comment by mikeerickson** [comment]
Great, let me know if you need any assistance.

**Comment by johndatserakis** [comment]
Ok great - this is now out in `v3.3.0` from this pr: https://github.com/johndatserakis/vue-simple-context-menu/pull/28.

**Comment by mikeerickson** [comment]
@johndatserakis Hey there, I see this was added, just got around to implementing and have a display issue I wanted you to review.

![image](https://user-images.githubusercontent.com/183153/96802740-4e673500-13bf-11eb-9cb5-64c5d341ce7f.png)

I am curious if there is something else I need (updated css?)

**Comment by johndatserakis** [comment]
Hey Mike,

Strange - yea the new css should just come when you upgraded your library.

The [live demo](https://johndatserakis.github.io/vue-simple-context-menu/) site is showing the divider without issue:

<img width="445" alt="Screen Shot 2020-10-21 at 9 49 40 PM" src="https://user-images.githubusercontent.com/9972969/96808754-7074ad80-13e7-11eb-8025-2b2088f078a4.png">

Hmm, I wonder what the issue could be. I just checked on Chrome, Safari, and Firefox all on a Mac and it was fine. What browser and computer are you looking on?

There is a little bit of a "dance" that I had to do to get the padding and height of the divider to play nice - but I'm not seeing any negative effects of that.

Are you adding any custom css that's overwriting the `.vue-simple-context-menu__divider` CSS by any chance? That could do it - like if you're overwriting the padding in total.

If you can provide a codepen or something demonstrating this I'd be more than happy to take a look and fix it.

Sorry for the issue.

**Comment by mikeerickson** [comment]
Hey John

I tried to make a codepen, but I always receive an error about the missing required parameter `elementId` (which I am definitely supplying).  

Here is a codepen that I started [Codedungeon vue-context-menu codepen](https://codepen.io/codedungeon/pen/ZEOBxdJ?editors=1000)

I have also created a quick Vue app (using vue cli) which can be found here:

[vue-simple-context-menu-test](https://github.com/mikeerickson/vue-simple-context-menu-test)

The repo shows the problem

![image](https://user-images.githubusercontent.com/183153/96877540-a2f5c900-142e-11eb-8f5d-7509c8db0897.png)

**Comment by johndatserakis** [comment]
Thank you @mikeerickson for the example - that was perfect and helped me find the problem right away. There was an issue with the `box-sizing` setting on the divider. I fixed it here: https://github.com/johndatserakis/vue-simple-context-menu/pull/33. I am putting out a new version now at `v3.3.2`.

Thank you for your help on this! Sorry about the issue.

**Comment by mikeerickson** [comment]
Awesome, glad it helped and you were able to cure.  I will be deploying on Monday 👍
