### ISSUE TITLE
Include fontawesome icons in contextual menu (use v-html)

### ISSUE THREAD

**Issue by mikeerickson** [johndatserakis/vue-simple-context-menu#34]
Hey there

I am trying to display fontawesome icons in my contextual menu, but alas it seems you are using simple interpolation

```js

<li
  v-for="(option, index) in options"
  :key="index"
  @click.stop="optionClicked(option)"
  class="vue-simple-context-menu__item"
  :class="[option.class, (option.type === 'divider' ? 'vue-simple-context-menu__divider' : '')]"
>
  {{option.name}}
</li>

```

![image](https://user-images.githubusercontent.com/183153/101053955-385f9f00-353d-11eb-8d9a-8f8b5053ce9b.png)

Would you consider making a small adjustment?

```js
<li
  v-for="(option, index) in options"
  :key="index"
  @click.stop="optionClicked(option)"
  class="vue-simple-context-menu__item"
  :class="[option.class, (option.type === 'divider' ? 'vue-simple-context-menu__divider' : '')]"
  v-html="option.name"
/>

```

**Comment by mikeerickson** [comment]
Here is how my option array is current defined. If you want to implement another method, I am all ears :-)

Note: The actual `detailMenu` needs to change at runtime so at some point in the app, the actual fontawesome menu class will change (to denote on/off) so I need to make sure the :options are indeed reactive.

```js

detailMenu: [
   {
       name: "<i class='far fa-check-square'></i> Active",
       slug: "contact-active",
   },
   {
       name: "<i class='fas fa-thumbtack'></i> Pinned",
       slug: "contact-pinned",
   },

],

```

**Comment by mikeerickson** [comment]
@johndatserakis Hey John, any chance on getting this supported?

**Comment by mikeerickson** [comment]
@johndatserakis Hey John, if you are keen to a PR, I have one ready.  Really quite simple in the event you just want to implement it on your end and push a new version (instead of dealing with the PR)

In `./src/vue-simple-context-menu.vue` change from

```js
{{ option.name }}
```

to


```js
<span v-html="option.name"></span>
```

I have tested all other functionality and no apparent issues, seems a pretty quick and dirty change

**Comment by johndatserakis** [comment]
Hey there @mikeerickson - sorry I seemed to have missed this initial issue, my bad.

Sure, let me quickly make that change now and push out a new version so you can use it. I'll do that right now.

**Comment by johndatserakis** [comment]
Closed via https://github.com/johndatserakis/vue-simple-context-menu/pull/35

**Comment by johndatserakis** [comment]
Thanks again @mikeerickson - new version is out at v3.4.0.

**Comment by mikeerickson** [comment]
Awesome, thanks John.  Much appreciated
