### ISSUE TITLE
Inline Template issues?

### ISSUE THREAD

**Issue by gbrits** [johndatserakis/vue-simple-context-menu#39]
It seems this doesn't play well with inline-templates? Have you tested it out in inline-templates? Just breaks the render with no errors in console for me unfortunately.

**Comment by gbrits** [comment]
I got it working by changing the `elementId` prop to kebab case and also by closing the tag verbatim:
```
<vue-simple-context-menu
        :element-id="'myUniqueId'"
        :options="earningsRateOptions"
        :ref="'vueSimpleContextMenu'"
        @option-clicked="rateOptionClicked"></vue-simple-context-menu>
```

**Comment by johndatserakis** [comment]
I've seen this in unrelated components before - I believe in some environments the props must be kebab-case. Usually you can get away with it, but because HTML is case insensitive, if you're using something in a certain way, you'll run into this with any Vue component.
