### ISSUE TITLE
Conditional suppress options in contextmenu?

### ISSUE THREAD

**Issue by rowild** [johndatserakis/vue-simple-context-menu#46]
Is it possible with this menu to somehow show  an option in the contextmenu only, when a certain condition is met?

In my case, i have an audio wave (on a canvas) where users can add markers of different "degrees"  (1, 2 or 3, let's say). Via rightclick it shall be possible to change a marker to another degree. However, if the marker is of degree 1, only 2 menu options shall be shown: those that change the marker to degree 2 or 3, but not 1.

Thank you! :-)

**Comment by johndatserakis** [comment]
Hey there - yup so for this case it's best to make a computed value for your options that is dynamic based on these `degrees` you mention. Doing that will allow you to have the options change as your parameters change.

**Comment by rowild** [comment]
@johndatserakis Thanks for your response! Yes, that did it! :-)
I am very happy with your context-menu!!!
