### ISSUE TITLE
Upgrade to Vue 3

### ISSUE THREAD

**Issue by danielelkington** [johndatserakis/vue-simple-context-menu#48]
Have raised a PR https://github.com/johndatserakis/vue-simple-context-menu/pull/47

I have also published a new npm package with Vue 3 support - [vue-3-simple-context-menu](https://www.npmjs.com/package/vue-3-simple-context-menu) in case the PR is not merged or Vue 3 support is not added in this repo.

**Comment by johndatserakis** [comment]
PR merged - thanks again.
