### ISSUE TITLE
How to add Submenu for context menu

### ISSUE THREAD

**Issue by Rajasekhar1989** [johndatserakis/vue-simple-context-menu#50]
I want to add Multiple Sub menus drop-downs for Context menu..

Thank you..

**Comment by johndatserakis** [comment]
Hey there - yea I agree that'd be a nice feature, but I think that may be out of scope for this library and my ability in terms of free time. There's a lot that goes into that in terms of considering different layouts, which I think would be better suited for a library aimed at tree management.
