### ISSUE TITLE
Trigger showMenu event on text selection

### ISSUE THREAD

**Issue by bhuvan-ganesan** [johndatserakis/vue-simple-context-menu#52]
Hi 

I am trying to find a way to add one more event to this lib
if a user select a text in div, can we trigger showMenu event 

Thanks for the help

**Comment by johndatserakis** [comment]
Hey there - sorry, I'm confused. What text, in what div are you referring to? The click event is already set up for the component. So if you want to add a click event to your own text, that sounds like something you can add on your side.

If you provide a code example I can perhaps help further.

**Comment by johndatserakis** [comment]
Let me know if you still have questions on this, thanks.
