### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by oldshaghat** [johndatserakis/vue-simple-context-menu#55]
Seeing a deprecation warning in Chrome for use of Event.path (should move to Event.composedPath() at some point) which looks like it's only in bit for the click-outside dependency (vue-simple-context-menu.esm.js:10)

**Comment by johndatserakis** [comment]
Thank you for the heads up. I'll take a look at this when I get a chance.

**Comment by johndatserakis** [comment]
Closing as complete due to the `click-outside-vue3` library using `Event.composedPath()` as a fallback, which now is the only var used there due to Event.path not being used anymore.
