### ISSUE TITLE
sideEffects vs css file inclusion

### ISSUE THREAD

**Issue by stephane-martin** [johndatserakis/vue-simple-context-menu#56]
(not a JS expert, please forgive me if imprecise)

When building an app using parcel/vue3, even though I include the CSS file (`import 'vue-simple-context-menu/dist/vue-simple-context-menu.css'`), the resulting distribution does not contain the style.

I think it's related to `sideEffects: false` in package.json. It may triggers parcel's scope hoisting (https://parceljs.org/features/scope-hoisting/).

Similar issue in another vue component: https://github.com/Vuepic/vue-datepicker/issues/526

**Comment by johndatserakis** [comment]
Thank you, updated.
