### ISSUE TITLE
Menu not staying displayed on Firefox 66+ (macOS)

### ISSUE THREAD

**Issue by davbtmx** [johndatserakis/vue-simple-context-menu#9]
Hi there – On macOS, since Firefox 66 (66.0.1 - 66.0.5, and 67.0), contextual menu does not stay displayed after the right-click. The problem also occurs on the demo page, if you right-click on Jim, Dwight, or Pam. I have no problem on Safari, and as far as I know it is working correctly on Windows with Firefox 66+.

**Comment by johndatserakis** [comment]
Hello - thanks for this bug report. I see what you're saying and yes the right-click portion is indeed closing right after opening in Firefox.

It's weird that the left click works without issue - definitely seems like something's up with the right click usage.

I will continue to research this as it might mean that Firefox is not listening to the `prevent` and `stop` on the `@contextmenu` handler in the example. The full line is `@contextmenu.prevent.stop="handleClick1($event, item)"`.

I found this issue that may be related: https://github.com/vuejs/vue/issues/9832. I'll add any more research here as I find it.

Thank you.

**Comment by ansidev** [comment]
@davbtmx: I 've tested on Firefox Stable 67.0.3. It 's same as your report. But everything is OK on Firefox Developer Edition 68.0b11. Both are running on macOS (10.14.5).
After researching, I found a workaround for this issue: https://elementaryos.stackexchange.com/questions/16475/firefox-right-click-issue

**Comment by davbtmx** [comment]
@ansidev: Indeed, after changing the param (mentionned in your link) in the config of Firefox 67.0.4 (macOS 10.13.6) it fixes the issue, and I have just tested the 68.0b12 in which the menu works fine. Thank you for the info!

**Comment by ansidev** [comment]
@johndatserakis We can close this issue!

**Comment by johndatserakis** [comment]
Great! Looks like the upcoming Firefox version fixes the issue. Thank you @ansidev!
